from __future__ import annotations

PRODUCTS: list[dict] = [
    {
        "id": "prod-creator-os",
        "name": "Creator OS for Notion",
        "creator": "Maya Chen",
        "category": "Productivity",
        "price_cents": 4900,
        "currency": "USD",
        "tags": ["notion", "creator-tools", "planning", "templates"],
        "rating": 4.7,
        "review_count": 86,
        "description": "A complete Notion workspace for independent creators to plan launches, track content, manage sponsors, and review monthly revenue.",
        "current": {
            "views": 1640,
            "sales": 39,
            "revenue_cents": 191100,
            "refunds": 2,
            "refund_cents": 9800,
            "discover_impressions": 890,
            "sources": [
                {"name": "Gumroad Discover", "views": 620, "sales": 8, "revenue_cents": 39200},
                {"name": "YouTube", "views": 410, "sales": 17, "revenue_cents": 83300},
                {"name": "Newsletter", "views": 280, "sales": 10, "revenue_cents": 49000},
                {"name": "Direct", "views": 330, "sales": 4, "revenue_cents": 19600},
            ],
        },
        "previous": {
            "views": 980,
            "sales": 43,
            "revenue_cents": 210700,
            "refunds": 1,
            "refund_cents": 4900,
            "discover_impressions": 510,
            "sources": [
                {"name": "Gumroad Discover", "views": 360, "sales": 11, "revenue_cents": 53900},
                {"name": "YouTube", "views": 220, "sales": 13, "revenue_cents": 63700},
                {"name": "Newsletter", "views": 210, "sales": 14, "revenue_cents": 68600},
                {"name": "Direct", "views": 190, "sales": 5, "revenue_cents": 24500},
            ],
        },
    },
    {
        "id": "prod-design-kit",
        "name": "Minimal Landing Page Kit",
        "creator": "Studio Northstar",
        "category": "",
        "price_cents": 2900,
        "currency": "USD",
        "tags": ["templates"],
        "rating": 4.9,
        "review_count": 132,
        "description": "A polished landing page starter kit with sections, components, and Figma references for SaaS launches.",
        "current": {
            "views": 720,
            "sales": 31,
            "revenue_cents": 89900,
            "refunds": 1,
            "refund_cents": 2900,
            "discover_impressions": 1800,
            "sources": [
                {"name": "Gumroad Discover", "views": 420, "sales": 11, "revenue_cents": 31900},
                {"name": "Product Hunt", "views": 130, "sales": 12, "revenue_cents": 34800},
                {"name": "X / Twitter", "views": 110, "sales": 6, "revenue_cents": 17400},
                {"name": "Direct", "views": 60, "sales": 2, "revenue_cents": 5800},
            ],
        },
        "previous": {
            "views": 540,
            "sales": 22,
            "revenue_cents": 63800,
            "refunds": 1,
            "refund_cents": 2900,
            "discover_impressions": 980,
            "sources": [
                {"name": "Gumroad Discover", "views": 300, "sales": 8, "revenue_cents": 23200},
                {"name": "Product Hunt", "views": 70, "sales": 5, "revenue_cents": 14500},
                {"name": "X / Twitter", "views": 95, "sales": 6, "revenue_cents": 17400},
                {"name": "Direct", "views": 75, "sales": 3, "revenue_cents": 8700},
            ],
        },
    },
    {
        "id": "prod-audio-pack",
        "name": "Cinematic Lo-Fi Sample Pack",
        "creator": "Arlo Vale",
        "category": "Music & Audio",
        "price_cents": 1900,
        "currency": "USD",
        "tags": ["music", "samples", "lo-fi", "ableton"],
        "rating": 4.1,
        "review_count": 24,
        "description": "Royalty-free drums, keys, tape textures, and melodic loops for producers working on cinematic lo-fi tracks.",
        "current": {
            "views": 910,
            "sales": 54,
            "revenue_cents": 102600,
            "refunds": 7,
            "refund_cents": 13300,
            "discover_impressions": 640,
            "sources": [
                {"name": "BeatStars", "views": 180, "sales": 20, "revenue_cents": 38000},
                {"name": "Gumroad Discover", "views": 330, "sales": 12, "revenue_cents": 22800},
                {"name": "Instagram", "views": 240, "sales": 17, "revenue_cents": 32300},
                {"name": "Direct", "views": 160, "sales": 5, "revenue_cents": 9500},
            ],
        },
        "previous": {
            "views": 760,
            "sales": 47,
            "revenue_cents": 89300,
            "refunds": 2,
            "refund_cents": 3800,
            "discover_impressions": 510,
            "sources": [
                {"name": "BeatStars", "views": 130, "sales": 13, "revenue_cents": 24700},
                {"name": "Gumroad Discover", "views": 280, "sales": 13, "revenue_cents": 24700},
                {"name": "Instagram", "views": 210, "sales": 15, "revenue_cents": 28500},
                {"name": "Direct", "views": 140, "sales": 6, "revenue_cents": 11400},
            ],
        },
    },
    {
        "id": "prod-zine-guide",
        "name": "Tiny Zine Launch Guide",
        "creator": "Riley Brooks",
        "category": "Writing & Publishing",
        "price_cents": 900,
        "currency": "USD",
        "tags": ["writing", "zines", "publishing"],
        "rating": 4.8,
        "review_count": 7,
        "description": "A short guide for planning, pricing, and shipping a first independent zine without overbuilding the launch.",
        "current": {
            "views": 84,
            "sales": 5,
            "revenue_cents": 4500,
            "refunds": 0,
            "refund_cents": 0,
            "discover_impressions": 120,
            "sources": [
                {"name": "Direct", "views": 32, "sales": 3, "revenue_cents": 2700},
                {"name": "Newsletter", "views": 28, "sales": 2, "revenue_cents": 1800},
                {"name": "Gumroad Discover", "views": 24, "sales": 0, "revenue_cents": 0},
            ],
        },
        "previous": {
            "views": 61,
            "sales": 4,
            "revenue_cents": 3600,
            "refunds": 0,
            "refund_cents": 0,
            "discover_impressions": 95,
            "sources": [
                {"name": "Direct", "views": 25, "sales": 2, "revenue_cents": 1800},
                {"name": "Newsletter", "views": 21, "sales": 2, "revenue_cents": 1800},
                {"name": "Gumroad Discover", "views": 15, "sales": 0, "revenue_cents": 0},
            ],
        },
    },
]


DASHBOARD_DATA: dict[str, dict] = {
    "prod-creator-os": {
        "churn": {"active_start": 142, "new_subscriptions": 18, "canceled": 6, "previous_active_start": 131, "previous_new_subscriptions": 12, "previous_canceled": 3, "revenue_lost_cents": 29400},
        "locations": [
            {"country": "United States", "region": "California", "views": 590, "sales": 18, "revenue_cents": 88200},
            {"country": "United Kingdom", "region": "England", "views": 210, "sales": 6, "revenue_cents": 29400},
            {"country": "Canada", "region": "Ontario", "views": 170, "sales": 5, "revenue_cents": 24500},
            {"country": "Australia", "region": "Victoria", "views": 95, "sales": 3, "revenue_cents": 14700},
        ],
        "utm_links": [
            {"source": "youtube", "medium": "video", "campaign": "launch-review", "destination": "Product page", "clicks": 320, "sales": 15, "revenue_cents": 73500},
            {"source": "newsletter", "medium": "email", "campaign": "creator-systems", "destination": "Product page", "clicks": 198, "sales": 9, "revenue_cents": 44100},
            {"source": "gumroad", "medium": "discover", "campaign": "recommended", "destination": "Product page", "clicks": 620, "sales": 8, "revenue_cents": 39200},
        ],
    },
    "prod-design-kit": {
        "churn": {"active_start": 88, "new_subscriptions": 9, "canceled": 2, "previous_active_start": 82, "previous_new_subscriptions": 6, "previous_canceled": 3, "revenue_lost_cents": 5800},
        "locations": [
            {"country": "United States", "region": "New York", "views": 260, "sales": 14, "revenue_cents": 40600},
            {"country": "Germany", "region": "Berlin", "views": 110, "sales": 5, "revenue_cents": 14500},
            {"country": "India", "region": "Karnataka", "views": 96, "sales": 4, "revenue_cents": 11600},
            {"country": "Brazil", "region": "Sao Paulo", "views": 74, "sales": 3, "revenue_cents": 8700},
        ],
        "utm_links": [
            {"source": "producthunt", "medium": "launch", "campaign": "kit-v2", "destination": "Product page", "clicks": 130, "sales": 12, "revenue_cents": 34800},
            {"source": "gumroad", "medium": "discover", "campaign": "recommended", "destination": "Product page", "clicks": 420, "sales": 11, "revenue_cents": 31900},
            {"source": "twitter", "medium": "social", "campaign": "template-thread", "destination": "Product page", "clicks": 110, "sales": 6, "revenue_cents": 17400},
        ],
    },
    "prod-audio-pack": {
        "churn": {"active_start": 64, "new_subscriptions": 11, "canceled": 5, "previous_active_start": 58, "previous_new_subscriptions": 9, "previous_canceled": 2, "revenue_lost_cents": 9500},
        "locations": [
            {"country": "United States", "region": "Georgia", "views": 280, "sales": 19, "revenue_cents": 36100},
            {"country": "Japan", "region": "Tokyo", "views": 140, "sales": 9, "revenue_cents": 17100},
            {"country": "France", "region": "Ile-de-France", "views": 115, "sales": 8, "revenue_cents": 15200},
            {"country": "Mexico", "region": "Jalisco", "views": 88, "sales": 5, "revenue_cents": 9500},
        ],
        "utm_links": [
            {"source": "beatstars", "medium": "marketplace", "campaign": "lofi-drums", "destination": "Product page", "clicks": 180, "sales": 20, "revenue_cents": 38000},
            {"source": "instagram", "medium": "social", "campaign": "reel-pack-demo", "destination": "Product page", "clicks": 240, "sales": 17, "revenue_cents": 32300},
            {"source": "gumroad", "medium": "discover", "campaign": "recommended", "destination": "Product page", "clicks": 330, "sales": 12, "revenue_cents": 22800},
        ],
    },
    "prod-zine-guide": {
        "churn": {"active_start": 24, "new_subscriptions": 3, "canceled": 0, "previous_active_start": 21, "previous_new_subscriptions": 2, "previous_canceled": 1, "revenue_lost_cents": 0},
        "locations": [
            {"country": "United States", "region": "Oregon", "views": 34, "sales": 2, "revenue_cents": 1800},
            {"country": "Canada", "region": "British Columbia", "views": 16, "sales": 1, "revenue_cents": 900},
            {"country": "United Kingdom", "region": "Scotland", "views": 12, "sales": 1, "revenue_cents": 900},
            {"country": "Netherlands", "region": "North Holland", "views": 8, "sales": 1, "revenue_cents": 900},
        ],
        "utm_links": [
            {"source": "newsletter", "medium": "email", "campaign": "tiny-launch", "destination": "Product page", "clicks": 28, "sales": 2, "revenue_cents": 1800},
            {"source": "direct", "medium": "direct", "campaign": "bookmarks-and-apps", "destination": "Product page", "clicks": 32, "sales": 3, "revenue_cents": 2700},
            {"source": "gumroad", "medium": "discover", "campaign": "recommended", "destination": "Product page", "clicks": 24, "sales": 0, "revenue_cents": 0},
        ],
    },
}
